name: Publish Docker image
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: nix-build docker.nix --argstr tag ${{ env.VERSION }}
      - run: nix-env -i skopeo -f '<nixpkgs>'

      - name: Push to Docker Hub 🐋
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTERY: docker.io
          TAG_NAME: ${{ env.REPO }}:${{ env.VERSION }}
        run: |
          sudo skopeo login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" $REGISTERY
          sudo skopeo copy --insecure-policy docker-archive:result docker://$REGISTERY/$TAG_NAME
       
      - name: Push to GitHub Packages 📦
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTERY: docker.pkg.github.com
          TAG_NAME: ${{ env.REPO }}/matrix-registration-image:${{ env.VERSION }}
        run: |
          sudo skopeo login --username="$GITHUB_USERNAME" --password="$GITHUB_PASSWORD" $REGISTERY
          sudo skopeo copy --insecure-policy docker-archive:result docker://$REGISTERY/$TAG_NAME
