name: Publish Docker Image
on:
  push:
      - '**'

strategy:
  matrix:
    arch:
	- 'import <nixpkgs> {}'
        # - 'import <nixpkgs> { crossSystem.config = "aarch64-unknown-linux-gnu"; }'
    hub: [Github, Docker]
    include:
	- hub: Github
	  registry: docker.pkg.github.com
	  username: ${{ github.actor }}
	  password: ${{ secrets.GITHUB_TOKEN }}
	- hub: Docker
	  registry: docker.io
	  username: ${{ secrets.DOCKER_USERNAME }}
	  password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ env.REPO }}:${{ env.VERSION }}

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: "echo 'VERSION=${GITHUB_REF#refs/*/}' >> $GITHUB_ENV"

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - run: nix-build docker.nix --arg '${{ matrix.arch }}' --argstr tag ${{ env.VERSION }}
      - run: nix-env -i skopeo -f '<nixpkgs>'

      - name: Push to ${{ matrix.hub }} 
        run: |:q
	  TAG=$GITHUB_REPOSITORY/matrix-registration-image:$VERSION
          sudo skopeo login --username="${{matrix.username}}" --password="${{matrix.password}}" ${{ matrix.registry }}
          sudo skopeo copy --insecure-policy docker-archive:result docker://${{ matrix.regisry }}/$TAG
